<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['genero'  =>  'masculino','descricao'  =>  'teste1','composicao'  =>  'NOBUQUE','referencia'  =>  'DTFT53','colecao_id'  =>  '1','numeracao_br'  =>  '33','numeracao_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'AMARELO','palmilha'  =>  'CONFORT','modelo_id'      =>  '1','acessorios'  =>  'extrais','salto'  =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '5','estoque'   =>  '10','preco'  =>  '54.3','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste2','composicao'  =>  'CAMURÇA','referencia'  =>  'DTFT54','colecao_id'  =>  '2','numeracao_br'  =>  '34','numeracao_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'AZUL','palmilha'     =>  'TRADICIONAL','modelo_id'  =>  '2','acessorios'  =>  'spaike','salto'   =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '3','estoque'   =>  '20','preco'  =>  '52.5','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste3','composicao'  =>  'VERNIZ','referencia'   =>  'DTFT55','colecao_id'  =>  '3','numeracao_br'  =>  '35','numeracao_eua'  =>  '8','tamanho'  =>  '','altura'  =>  '','cor'  =>  'PRETO','palmilha'    =>  'PRETO','modelo_id'        =>  '3','acessorios' =>  'ilhos','salto'    =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '4','estoque'   =>  '30','preco'  =>  '45.23','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste4','composicao'  =>  'NAPA','referencia'     =>  'DTFT56','colecao_id'  =>  '4','numeracao_br'  =>  '35','numeracao_eua'  =>  '9','tamanho'  =>  '','altura'  =>  '','cor'  =>  'BRANCO','palmilha'   =>  'BEJE','modelo_id'         =>  '4','acessorios'  =>  'cardaço','salto'  =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '2','estoque'   =>  '12','preco'  =>  '12.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste5','composicao'  =>  'FLORA','referencia'    =>  'DTFT57','colecao_id'  =>  '1','numeracao_br'  =>  '38','numeracao_eua'  =>  '10','tamanho' =>  '','altura'  =>  '','cor'  =>  'CIANO','palmilha'    =>  'MARFIM','modelo_id'       =>  '2','acessorios'  =>  'extrais','salto'  =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '5','estoque'   =>  '20','preco'  =>  '15.25','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste6','composicao'  =>  'NOBUQUE','referencia'  =>  'DTFT58','colecao_id'  =>  '2','numeracao_br'  =>  '39','numeracao_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'CAJU','palmilha'     =>  'CONFORT','modelo_id'      =>  '1','acessorios'  =>  'spaike','salto'   =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '3','estoque'   =>  '30','preco'  =>  '13.32','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste7','composicao'  =>  'CAMURÇA','referencia'  =>  'DTFT59','colecao_id'  =>  '3','numeracao_br'  =>  '40','numeracao_eua'  =>  '8','tamanho'  =>  '','altura'  =>  '','cor'  =>  'CIANO','palmilha'    =>  'TRADICIONAL','modelo_id'  =>  '2','acessorios'  =>  'ilhos','salto'    =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '10','estoque'  =>  '23','preco'  =>  '18.23','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste8','composicao'  =>  'VERNIZ','referencia'   =>  'DTFT60','colecao_id'  =>  '4','numeracao_br'  =>  '41','numeracao_eua'  =>  '5','tamanho'  =>  '','altura'  =>  '','cor'  =>  'PRETO','palmilha'    =>  'PRETO','modelo_id'        =>  '3','acessorios'  =>  'cardaço','salto'  =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '16','estoque'  =>  '1','preco'   =>  '35.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste9','composicao'  =>  'NAPA','referencia'     =>  'DTFT61','colecao_id'  =>  '3','numeracao_br'  =>  '33','numeracao_eua'  =>  '4','tamanho'  =>  '','altura'  =>  '','cor'  =>  'LILAS','palmilha'    =>  'BEJE','modelo_id'         =>  '4','acessorios'  =>  'extrais','salto'  =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '50','estoque'  =>  '12','preco'  =>  '33.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste10','composicao' =>  'FLORA','referencia'    =>  'DTFT62','colecao_id'  =>  '2','numeracao_br'  =>  '32','numeracao_eua'  =>  '3','tamanho'  =>  '','altura'  =>  '','cor'  =>  'LILAS','palmilha'    =>  'MARFIM','modelo_id'       =>  '3','acessorios'  =>  'spaike','salto'   =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '25','estoque'  =>  '50','preco'  =>  '49.9','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto']
        ]);
        $this->command->info('products importadas com sucesso!');

    }
}
