<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['genero'  =>  'masculino','descricao'  =>  'teste1','composicao'  =>  'NOBUQUE','referencia'  =>  'DTFT53','colecao'  =>  'MANUELA','numero_br'  =>  '33','numero_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'AMARELO','palmilha'  =>  'CONFORT','modelo'      =>  'plataforma','acessorios'  =>  'extrais','salto'  =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '5','estoque'   =>  '10','preco'  =>  '54.3','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste2','composicao'  =>  'CAMURÇA','referencia'  =>  'DTFT54','colecao'  =>  'LUXO','numero_br'     =>  '34','numero_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'AZUL','palmilha'     =>  'TRADICIONAL','modelo'  =>  'scarpin','acessorios'     =>  'spaike','salto'   =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '3','estoque'   =>  '20','preco'  =>  '52.5','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste3','composicao'  =>  'VERNIZ','referencia'   =>  'DTFT55','colecao'  =>  'MARINA','numero_br'   =>  '35','numero_eua'  =>  '8','tamanho'  =>  '','altura'  =>  '','cor'  =>  'PRETO','palmilha'    =>  'PRETO','modelo'        =>  'ana bela','acessorios'    =>  'ilhos','salto'    =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '4','estoque'   =>  '30','preco'  =>  '45.23','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste4','composicao'  =>  'NAPA','referencia'     =>  'DTFT56','colecao'  =>  'JULIA','numero_br'    =>  '35','numero_eua'  =>  '9','tamanho'  =>  '','altura'  =>  '','cor'  =>  'BRANCO','palmilha'   =>  'BEJE','modelo'         =>  'sapatilha','acessorios'   =>  'cardaço','salto'  =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '2','estoque'   =>  '12','preco'  =>  '12.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste5','composicao'  =>  'FLORA','referencia'    =>  'DTFT57','colecao'  =>  'MANUELA','numero_br'  =>  '38','numero_eua'  =>  '10','tamanho' =>  '','altura'  =>  '','cor'  =>  'CIANO','palmilha'    =>  'MARFIM','modelo'       =>  'plataforma','acessorios'  =>  'extrais','salto'  =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '5','estoque'   =>  '20','preco'  =>  '15.25','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste6','composicao'  =>  'NOBUQUE','referencia'  =>  'DTFT58','colecao'  =>  'LUXO','numero_br'     =>  '39','numero_eua'  =>  '7','tamanho'  =>  '','altura'  =>  '','cor'  =>  'CAJU','palmilha'     =>  'CONFORT','modelo'      =>  'scarpin','acessorios'     =>  'spaike','salto'   =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '3','estoque'   =>  '30','preco'  =>  '13.32','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste7','composicao'  =>  'CAMURÇA','referencia'  =>  'DTFT59','colecao'  =>  'MARINA','numero_br'   =>  '40','numero_eua'  =>  '8','tamanho'  =>  '','altura'  =>  '','cor'  =>  'CIANO','palmilha'    =>  'TRADICIONAL','modelo'  =>  'ana bela','acessorios'    =>  'ilhos','salto'    =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '10','estoque'  =>  '23','preco'  =>  '18.23','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'feminino','descricao'   =>  'teste8','composicao'  =>  'VERNIZ','referencia'   =>  'DTFT60','colecao'  =>  'JULIA','numero_br'    =>  '41','numero_eua'  =>  '5','tamanho'  =>  '','altura'  =>  '','cor'  =>  'PRETO','palmilha'    =>  'PRETO','modelo'        =>  'sapatilha','acessorios'   =>  'cardaço','salto'  =>  'bloco','solado'  =>  'tr','imagem'      =>  '','desconto'  =>  '16','estoque'  =>  '1','preco'   =>  '35.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'unissex','descricao'    =>  'teste9','composicao'  =>  'NAPA','referencia'     =>  'DTFT61','colecao'  =>  'MANUELA','numero_br'  =>  '33','numero_eua'  =>  '4','tamanho'  =>  '','altura'  =>  '','cor'  =>  'LILAS','palmilha'    =>  'BEJE','modelo'         =>  'plataforma','acessorios'  =>  'extrais','salto'  =>  'taça','solado'   =>  'sofort','imagem'  =>  '','desconto'  =>  '50','estoque'  =>  '12','preco'  =>  '33.20','descricaolonga'  =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto'],
            ['genero'  =>  'masculino','descricao'  =>  'teste10','composicao' =>  'FLORA','referencia'    =>  'DTFT62','colecao'  =>  'LUXO','numero_br'     =>  '32','numero_eua'  =>  '3','tamanho'  =>  '','altura'  =>  '','cor'  =>  'LILAS','palmilha'    =>  'MARFIM','modelo'       =>  'scarpin','acessorios'     =>  'spaike','salto'   =>  'fino','solado'   =>  'pvc','imagem'     =>  '','desconto'  =>  '25','estoque'  =>  '50','preco'  =>  '49.9','descricaolonga'   =>  'Qualquer justificativa que alimente as informações necessárias','detalhe'  =>  'Qualquer justificativa que alimente as informações necessárias para a fabricação do produto']
        ]);
        $this->command->info('products importadas com sucesso!');

    }
}
